name: CI

on:
  push:
  pull_request:
    branches-ignore:
      - "prod"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package.json') }}

      - name: install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: lint
        run: yarn run lint

      - name: build
        run: |
          cp ./src/Config/example.ts ./src/Config/index.ts
          yarn build
